### ISSUE TITLE
Combobox bad binding with flow 1.0.4

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-combo-box-flow#122]
Forwarded from https://github.com/vaadin/vaadin-combo-box/issues/716

### Description
With flow 1.0.4, binding fail the first time after an edit. (based on brewery webapp)

### Expected outcome
Correct binding

### Actual outcome
Empty binding

### Code :
> @Id("type")
> private ComboBox<String> doctorSent;
> 
> public EntryEditor() 
> {
> 	ListDataProvider<String> roleProvider = DataProvider.ofItems("", "Médecin 1", "Médecin 2", "Médecin 3", "Médecin 4");
> 			
> 	doctorSent.setDataProvider(roleProvider);
> 
> 	binder.forField(suivi)
> 		.withValidator(suiv -> !StringUtils.isBlank(suiv) || !StringUtils.isBlank(doctorSent.getValue()) 
> 			, "Le suivi ou le médecin envoyé doit être rempli")
> 		.bind("suivi");
> 
> 	//binder.bind(doctorSent, "sentDoctor");
> 	binder.forField(doctorSent)
> 	.withValidator(docsent -> !StringUtils.isBlank(docsent) || !StringUtils.isBlank(suivi.getValue()) 
> 		, "Le suivi ou le médecin envoyé doit être rempli")
> 	.bind("sentDoctor");
> }
> 
> public void read(Entry entry) 
> {
> 		//added to clean the bean before bind
> 		binder.removeBean();
> 		
> 		binder.readBean(entry);
> 		
> 		//Added to try to force bind
> 		doctorSent.setValue(entry.getSentDoctor());
> }

It was working fine in vaadin flow 1.0.0.rc5, when I've updated today to 1.0.4, it was broken. Reverted to rc5 : working.

**Comment by mikotin** [comment]
Sounds similar to #118 . Could you give it a try update to flow 1.0.5 ? Fix for similar issues in flow 1.0.4 with combobox are fixed with combobox 1.0.7

**Comment by ZheSun88** [comment]
@Nightbringer42 Could you try to update flow according to @mikotin 's advice? Or later, you could update platform check here https://github.com/vaadin/platform/releases.

**Comment by Nightbringer42** [comment]
Just tried to update to 10.0.5, vaadin-bom 10.0.5 does not exist and adding the dependencies flow  1.0.5 and vaadin-combo-box-flow 1.0.7 does not solve the problem.

**Comment by mikotin** [comment]
Ok, could you come up with minimal (full) code that produces the problem?

**Comment by Nightbringer42** [comment]
It would be really painful to get all that code, I think my bug is the same as #118, I'll just wait to have the vaadin-bom 10.0.5, I suppose that my pom don't override dependencies as it should...

**Comment by mikotin** [comment]
I feel your pain. That #118 was rather hard debug also. I was hoping to get an easy way to replicate that issue. :)

If you haven't already tested, you could give it a try adding
```
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-combo-box-flow</artifactId>
            <version>1.0.7</version>
        </dependency>
```

In you pom -file in <dependencies> -section and make sure that dependencies are refreshed.
