### ISSUE TITLE
Focusing ComboBox breaks dialogs

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-combo-box-flow#139]
When a `ComboBox` is focused in a nested `Dialog` or `ConfirmDialog`, its overlay covers the dialog and no further action is possible but closing the dialog pressing <kbd>Esc</kbd>.

![nested-dialog-combo-box-small](https://user-images.githubusercontent.com/851745/46875567-4d988180-ce3c-11e8-945e-38644390a678.gif)

Demo at: https://github.com/heruan/vaadin-spring-demo

**Comment by heruan** [comment]
With `Dialog` the behavior is different: after focusing the combo box the dialog closes anywhere you click (as if the click were always outside the dialog).

**Comment by heruan** [comment]
This is `awaits another ticket`, but which one? So to keep an eye on it 🙂

**Comment by pleku** [comment]
@heruan it was this one https://github.com/vaadin/vaadin-overlay/pull/130

Sorry I've missed the ping.

**Comment by heruan** [comment]
Thank you @pleku for the reference. Which action should be taken now to fix this (if any)? Not sure yet what triggers this, but some users reported the same kind of "freezing" also in non-nested dialogs.

**Comment by pleku** [comment]
The fix has been released in `vaadin-overlay` 3.1 and 3.2, so any component that depends on overlay should get the fix once those update to a version that uses either of the aforementioned versions...

**Comment by heruan** [comment]
Thank you @pleku, unfortunately I'm still experiencing this (or a very similar) issue with the latest releases.

Many users have reported that dialogs freeze and I was able to replicate the freeze in a sample project: [ComboBoxFreezingDialog.java](https://github.com/heruan/vaadin-spring-demo/blob/891dcefe01d30f23e945df9646db2317f8549798/src/main/java/to/lova/vaadin/spring/ComboBoxFreezingDialog.java)

I wasn't able to determine clear replication steps, so I'm kinda rage-clicking everywhere until it freezes, but users have reported this with normal use; no client or server errors though.

![freezing-dialog](https://user-images.githubusercontent.com/851745/48697273-8d454c80-ebe4-11e8-91c3-7d7dd3a43c19.gif)

Tell me if I need to open this elsewhere or if we can continue the discussion here.

**Comment by pleku** [comment]
Sorry for my crappy answer, but after now looking at the versions, https://github.com/vaadin/platform/pull/352/files gives me the conclusion that it should be fixed in eg. `12.0.0.beta1` and `beta2`. So if it still reproduces, probably worth opening another issue issue in overlay/combobox/dialog ... or just commenting on vaadin/vaadin-overlay#130

**Comment by pleku** [comment]
@heruan you could also verify that in your project the webjar dependency version for `overlay` is either 3.1.1. or 3.2.1 ?

**Comment by heruan** [comment]
The `vaadin-overlay` WebJar is at 3.2.1 (pulled from 12.0.0.beta2 BOM). So I guess this is a different issue, I'm just not sure if I should open this on `overlay`, `combo-box` or `dialog` 😕

**Comment by heruan** [comment]
Further investigating I've found that it's the `vaadin-dialog` backdrop which blocks everything, so I opened a new issue there: https://github.com/vaadin/vaadin-dialog/issues/123

**Comment by web-padawan** [comment]
Note: vaadin/vaadin-dialog#123 has been fixed by vaadin/vaadin-overlay#137 and there has been few more fixes in overlay, included to V12 and V13 platform releases. So I'm closing this issue as fixed.
